beacon_endpoint_domain="example.com"
beacon_endpoint_port="51820"
interface="wg0"

beacon_wireguard_private_key="2B4bIZm2UJKcdz0qZgx/vwj0FLjBpykfX040VCGeIVk="
beacon_wireguard_public_key="fgRvmi1ycNmZNNGpozXZleHmEMpDbzNbXaxb6KfVuSs="
satellite_wireguard_private_key="YOwjb1104NDWKflq3UXwWsIa+NQs1V75Gsgb7tvN6WM="
satellite_wireguard_public_key="sbvdvhdJyH3yceXc3xNADbIK51ruWeqx/esapg+H3BE="